spring:
  application:
    name: Tomcat_demo
  datasource:
    url: jdbc:postgresql://localhost:5432/HealthCare
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update 
      
 
server:
  port: 9091

